version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - app-net

  scraper:
    build:
      context: ./scraper
    container_name: scraper
    depends_on:
      - mongodb
    env_file:
      - ./scraper/.env
    networks:
      - app-net
    volumes:
      - ./scraper:/app
    restart: always

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev
    env_file:
      - ./backend/.env
    depends_on:
      - scraper
    networks:
      - app-net
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-net
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always

volumes:
  mongo_data:


networks:
  app-net:
    driver: bridge
